title: Ion Trap
tagline: Trapped Ions Quantum Computer
owner: iontrapnet
link: http://www.iontrap.net
copyright: '&copy;&nbsp;<a href="http://www.iontrap.net">IonTrap.Net</a>'

highlighter: rouge
permalink: pretty
markdown: kramdown
kramdown:
    input: GFM
    math_engine: mathjax
    auto_ids: true
#markdown: redcarpet
#redcarpet:
#    extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "highlight", "quote", "footnotes", "strikethrough", "with_toc_data"]
gems:
  - jekyll-sitemap
  
exclude: [README.md]
